Fixed Testing

diff --git a/.github/workflows/aur.yml b/.github/workflows/aur.yml
--- a/.github/workflows/aur.yml
+++ b/.github/workflows/aur.yml
@@ -498,13 +498,18 @@ jobs:
         run: patch -Np1 -i ./scripts/pacman_repo.patch /etc/pacman.conf
       
       - name: Intall Packages
+        shell: bash -l {0}
         run: |
-          python3 -c "import json5, json; json.dump(json5.load(open('packages_aur.json', 'r')), open('packages_aur.json', 'w'))"
+          python3 ./scripts/prepare_test_packages.py
 
-          cat packages_aur.json | jq .[].name -r > packages_aur.txt
           while read -r package; do
-              echo "=================== Installing $package ==================="
+              echo -e "\e[1m\e[32m =================================== Installing '$package' =================================== \e[0m"
               pacman -Sy --noconfirm --color always --ask 4 --overwrite '*' $package 
-              echo "==========================================================="
+
+              if [[ $? != 0 ]] ; then
+                echo -e "\e[1m\e[31m ============================== Failed to install '$package' ============================== \e[0m"
+              fi
+
+              echo -e "\e[1m\e[33m =========================================================================================== \e[0m"
           done < packages_aur.txt
 
