Update aur.yml

diff --git a/.github/workflows/aur.yml b/.github/workflows/aur.yml
--- a/.github/workflows/aur.yml
+++ b/.github/workflows/aur.yml
@@ -81,7 +81,7 @@ jobs:
           || \
           sudo -u user yay -Sy --noconfirm --needed --builddir . --nocleanafter --editmenu --answeredit All --print ${{ matrix.depends }} \
           || \
-          echo "[Error] Can not install dependencies" && exit 1
+          ( echo "[Error] Can not install dependencies" && exit 1 )
 
       - name: Build ${{ matrix.name }}
         run: sudo -u user yay -Sy --noconfirm --needed --builddir . --nocleanafter --editmenu --answeredit All --editor sed --editorflags "'s/epoch=/#epoch=/g'" --print --aur ${{ matrix.name }}
@@ -94,6 +94,8 @@ jobs:
   #         sudo -u user makepkg --noconfirm -si
   #         mv *.pkg.tar.zst ..
 
+      - run: find . -iname *.pkg.tar.zst -exec cp {} . \;
+
       - run: ls -lRh
         if: always()
 
@@ -101,13 +103,9 @@ jobs:
         uses: actions/upload-artifact@v3
         with:
           name: "${{ matrix.name }}"
-          path: |
-            ./*/*.pkg.tar.zst
-            *.pkg.tar.zst
-
+          path: "*.pkg.tar.zst"
 
   deploy:
-    name: "Build ${{ matrix.name }}"
     needs: [build]
     runs-on: ubuntu-latest
     
